# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#
#                 NaturalVanish
#               Author: CyberRyan
#            Discord: CyberRyan#8381
#
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-


# Welcome to the configuration file for the NaturalVanish plugin!
# Supports the standard color codes in Minecraft (see https://minecraft.gamepedia.com/Formatting_codes)
# Note: maximum level is level 5. Anything above 5 will not work.

#
# Command information:
# () = required, [] = optional
#

#
# NaturalVanish Config Variables:
# [PLAYER] = Player name
# [ARG] = Argument in the command (ex: /vanish toggle (player) would return the 2nd arg)
#

#
# All the configuration for any subcommands in /vanish
#
vanish:

  #
  # General Configuration
  #

  # Permission to use any vanish commands
  # Required for all commands
  permission: "naturalvanish.use"

  # What to send when the command sender doesn't have the above permission
  permission-msg: "&cYou lack the permission to do this command!"

  # The primary color of all messages
  # Note: in the rest of this config, you can use "&p" as a shortcut for this color
  primary-color: "&a"

  # The secondary color of all messages
  # Note: in the rest of this config, you can use "&s" as a shortcut for this color
  secondary-color: "&7"

  # Should a player with operator be granted access to all vanish commands?
  op-override: true

  # What to send if the sender can't execture a command
  # Example: a command block trying to run /vanish
  cant-use-msg: "&cYou can only do this as a player!"


  #
  # /vanish
  #
  use:

    flight:

      # Should the player's flight mode be activated when they vanish?
      enable: true

      # When a player unvanishes, should their flight mode be reset back to their flight mode before they vanished?
      reset: true

      # What the player's flight speed will be set to when they vanish
      # 1 = normal, 2 = twice as fast, etc.
      speed: 1

    # What the player's walking speed will be set to when they vanish
    # 1 = normal, 2 = twice as fast, etc.
    walk-speed: 1

    # Should the player receive night vision when they vanish?
    night-vision: true

    # Should the player be able to see themselves when they are vanished?
    see-self: false

    # Should the player's helmet be set to their skull when they vanish?
    skull-helmet: true

    bossbar:

      # Should a bossbar be sent to vanished players?
      enable: true

      # What the title/text is on the bossbar
      # [LEVEL] = player's vanish level
      title: "&pCurrently Vanished &8(&sLevel [LEVEL]&8)"

      # The color of the bossbar
      # Colors: blue, green, pink, purple, red, white, or yellow
      color: "white"

      # The percentage of the bar that is filled
      # 100 = full, 0 = empty
      percent: 100


  #
  # /vanish setlevel (level)
  #
  level:

    # What the permission should be to use this command
    permission: "naturalvanish.setlevel"

    # What to send when the level provided is higher than the player's maximum level
    high-msg: "&sThat level is higher than your maximum level!"

    # What to send when the level provided isn't between 1 and 5
    invalid-level-msg: "&sYour vanish level must be between &p1&s and &p5"

    # Levels
    # Important note: adding any level will give the player access to all the levels below it as well
    1:
      # Permission for this is automatically given with the command permission

      # What to send when a player with level one vanishes
      enable-msg: "&p[PLAYER] &shas vanished &8(&sLevel 1&8)"

      # What to send when a player with level one unvanishes
      disable-msg: "&p[PLAYER] &shas unvanished"

    2:
      # Permission for level two vanish
      permission: "naturalvanish.level.2"

      # What to send when a player with level one vanishes
      enable-msg: "&p[PLAYER] &shas vanished &8(&sLevel 2&8)"

      # What to send when a player with level one unvanishes
      disable-msg: "&p[PLAYER] &shas unvanished"

    3:
      # Permission for level two vanish
      permission: "naturalvanish.level.3"

      # What to send when a player with level one vanishes
      enable-msg: "&p[PLAYER] &shas vanished &8(&sLevel 3&8)"

      # What to send when a player with level one unvanishes
      disable-msg: "&p[PLAYER] &shas unvanished"

    4:
      # Permission for level two vanish
      permission: "naturalvanish.level.4"

      # What to send when a player with level one vanishes
      enable-msg: "&p[PLAYER] &shas vanished &8(&sLevel 4&8)"

      # What to send when a player with level one unvanishes
      disable-msg: "&p[PLAYER] &shas unvanished"

    5:
      # Permission for level two vanish
      permission: "naturalvanish.level.5"

      # What to send when a player with level one vanishes
      enable-msg: "&p[PLAYER] &shas vanished &8(&sLevel 5&8)"

      # What to send when a player with level one unvanishes
      disable-msg: "&p[PLAYER] &shas unvanished"


  #
  # /vanish setlevel (player) (level)
  #
  level-others:

    # What the permission should be to use this command
    permission: "naturalvanish.setlevel.others"

    # What to send if the player-argument has never joined the server before
    not-joined-msg: "&p[ARG]&s has never joined the server before!"


  # /vanish toggle (player)
  toggle:

    # What the permission should be to use this command
    permission: "naturalvanish.toggle.others"

    # What to send if the sender's maximum level is lower than the target's current level
    level-low-msg: "&p[ARG]&s's level is higher than yours!"

    # What to send if the target has never joined the server before
    not-joined-msg: "&p[ARG]&s has never joined the server before!"

    # What to send to the sender if...
    sender:
      # ... target is online and their vanish was enabled
      enabled: "&pEnabled&s the vanish for &p[ARG]"

      # ... target is online and their vanish was disabled
      disabled: "&cDisabled&s the vanish for &p[ARG]"

      # ... target is offline and their vanish was enabled
      off-enabled: "&pEnabled&s the vanish for &p[ARG]&s when they next join"

      # ... target is offline and their vanish was disabled
      off-disabled: "&cDisabled&s the vanish for &p[ARG]&s when they next join"

    # What to sender to the target if...
    target:
      # ... target is online and their vanish was enabled
      enabled: "&sYour vanish has been &penabled"

      # ... target is online and their vanish was disabled
      disabled: "&sYour vanish has been &cdisabled"

      # ... target was offline and their vanish was enabled
      off-enabled: "&sYour vanish has been &penabled&s while you were offline"

      # ... target was offline and their vanish was disabled
      off-disabled: "&sYour vanish has been &cdisabled&s while you were offline"


  #
  # /vanish checklevel
  #
  checklevel:

    # What the permission should be to use this command
    permission: "naturalvanish.checklevel"


  #
  # /vanish checklevel (player)
  #
  checklevel-other:

    # What the permission should be to use this command
    permission: "naturalvanish.checklevel.others"

    # What to send if the target hasn't joined the server before
    not-joined-msg: "&p[ARG]&s has never joined the server before!"


  #
  # /vanish check
  #
  check:

    # What the permission should be to use this command
    permission: "naturalvanish.check"


  #
  # /vanish check (player)
  #
  check-other:

    # What the permission should be to use this command
    permission: "naturalvanish.check.others"


  #
  # /vanish list
  #
  list:

    # What the permission should be to use this command
    permission: "naturalvanish.list"

    # What the permission should be to see all vanished players, no matter the player's maximum level
    permission-all: "naturalvanish.list.all"


  #
  # /vanish reload
  #
  reload:

    # What the permission should be to use this command
    permission: "naturalvanish.reload"


  #
  # When an event is cancelled
  #
  cancel:

    # What to send when the player tries to grab the skull helmet while vanished
    # Only works if skull helmet is true
    skull: "&sYou cannot get this item while vanished!"


  #
  # When a vanished player joins the server
  #
  join:

    # Should the join message be cancelled
    cancel-msg: true


  #
  # When a vanished player leaves the server
  #
  leave:

    # Should the leave message be cancelled
    cancel-msg: true

    # Should the player's vanish be disabled (true) when they leave while vanished or should it stay enabled (false)
    disable: false


  #
  # Other events
  #
  other-events:
    # Note: for any of the messages in this section, setting them to "" will not send the message

    # When a vanished player tries to pickup an item
    item-pickup:

      # Should the event be cancelled
      cancel: true

      # What the message should be sent if it was cancelled
      cancel-msg: "&sYou cannot pickup items while vanished"

      # If the bypass permission (below) should be enabled
      bypass: true

      # The permission to bypass this event being canelled
      bypass-perm: "naturalvanish.itempickup.bypass"

    # When a vanished player tries to drop an item
    item-drop:
      cancel: true
      cancel-msg: "&sYou cannot drop items while vanished"
      bypass: true
      bypass-perm: "naturalvanish.itemdrop.bypass"

    # When a vanished player opens a chest, trapped chest, or enderchest
    chest-open:

      # Should the opening be silenced
      silent: true

      # What the message should be sent if it was silenced
      silent-msg: ""

    # When a vanished player interacts with blocks, like pressure plates, buttons, etc.
    interact:
      cancel: true
      cancel-msg: "&sYou cannot interact with redstone items while vanished"
      bypass: true
      bypass-perm: "naturalvanish.redstone.bypass"

    # When a vanished player takes any type of damage
    damage:
      cancel: true

    # When a vanished player attacks another player
    pvp:
      cancel: true
      cancel-msg: "&sYou cannot hit others while vanished"
      bypass: true
      bypass-perm: "naturalvanish.pvp.bypass"

    # When a vanished player places or breaks a block
    build:
      cancel: true
      cancel-msg: "&sYou cannot build while vanished"
      bypass: true
      bypass-perm: "naturalvanish.build.bypass"

    # When a vansihed player's hunger changes
    hunger:
      cancel: true